pipeline:

  build_docker_image:
    image: docker:17.07.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_docker_squidproxy" -p="$${DOCKER_PASSWORD}" quay.io
      - docker build -t squidproxy:$${DRONE_COMMIT_SHA} .

  latest_image_to_quay:
    image: docker:17.07.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_docker_squidproxy" -p="$${DOCKER_PASSWORD}" quay.io
      - docker tag squidproxy:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/squidproxy:latest
      - docker tag squidproxy:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/squidproxy:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/squidproxy:latest
      - docker push quay.io/ukhomeofficedigital/squidproxy:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:1.12
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_docker_squidproxy" -p="$${DOCKER_PASSWORD}" quay.io
      - docker tag squidproxy:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/squidproxy:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/squidproxy:$${DRONE_TAG}
    when:
      event: tag
